Repository HottoCoffee/HottoCoffee, pull requests merged in 2023-07, with the labels that each got.

#138 [Backend] Clean up Go CI files
  .github/dependabot.yaml
  .github/label-path-mapping.yaml
  .github/workflows/backend-integration-test.yaml
  .github/workflows/build-backend.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/deploy-backend.yaml
Labels: ci

#77 Add v1.1.0 schema
  swagger/schema/main.yaml
  swagger/schema/schemas/user.yaml
  swagger/schema/schemas/workspace.yaml
Labels: swagger

#151 [Backend](/sign-in) DB migration
  backend/db/create.sql
  backend/rust/Cargo.lock
  backend/rust/Cargo.toml
  backend/rust/migrations/20230723140811_user.sql
  backend/rust/src/main.rs
Labels: db
