Repository HottoCoffee/HottoCoffee, pull requests merged in 2023-06, with the labels that each got.

#67 [Backend] GET /api/batch/{batch_id}/history/{history_id}
  .github/workflows/backend-integration-test.yaml
  backend/db/create.sql
  backend/go/.mock/core/history_repository.go
  backend/go/.mock/usecase/history_output_boundary.go
  backend/go/controller/history_presenter.go
  backend/go/core/entity/batch.go
  backend/go/core/entity/batch_execution_history.go
  backend/go/core/entity/batch_execution_history_test.go
  backend/go/core/entity/cron_setting.go
  backend/go/core/entity/domain_rule_violation_error.go
  backend/go/core/entity/domain_rule_violation_error_test.go
  backend/go/core/entity/history.go
  backend/go/core/entity/history_test.go
  backend/go/core/history_repository.go
  backend/go/infrastructure/batch_repository_impl_test.go
  backend/go/infrastructure/history_repository_impl.go
  backend/go/infrastructure/history_repository_impl_test.go
  backend/go/main.go
  backend/go/main_test.go
  backend/go/usecase/get_history_usecase.go
  backend/go/usecase/get_history_usecase_test.go
  backend/go/usecase/history_output_boundary.go
  codecov.yaml
Labels: ci, backend, db

#117 Feature/auto deploy backend
  .github/workflows/build-backend.yaml
Labels: ci

#115 Set null for finish datetime
  swagger/schema/schemas/history.yaml
Labels: swagger

#118 fix CD
  .github/workflows/build-backend.yaml
  .github/workflows/deploy-backend.yaml
Labels: ci

#120 Feature/complete cd
  .github/workflows/deploy-backend.yaml
Labels: ci

#121 Use workflow name for trigger
  .github/workflows/deploy-backend.yaml
Labels: ci
